import { prisma } from "@/lib/prisma";
import type { Prisma } from "@/app/generated/prisma/client";

type EvidenceSlot = "front" | "back";

// select (not include) so binary photo bytes never load into this list —
// same reasoning as sanction.repository.ts's withDetails.
const publicSelect = {
  id: true,
  matchId: true,
  slot: true,
  photoType: true,
  uploadedByUserId: true,
  createdAt: true,
} as const;

export const matchEvidenceRepository = {
  findByMatchId(matchId: string) {
    return prisma.matchEvidence.findMany({
      where: { matchId },
      select: publicSelect,
      orderBy: { slot: "desc" }, // "front" > "back" alphabetically — desc puts front first
    });
  },

  findById(id: string) {
    return prisma.matchEvidence.findUnique({ where: { id }, select: publicSelect });
  },

  findPhoto(id: string) {
    return prisma.matchEvidence.findUnique({ where: { id }, select: { photo: true, photoType: true } });
  },

  // One row per (match, slot) — uploading again to an already-filled slot
  // replaces its photo ("retake") instead of accumulating extra rows.
  upsert(data: { matchId: string; slot: EvidenceSlot; photo: Buffer; photoType: string; uploadedByUserId: string }) {
    const { matchId, slot, ...rest } = data;
    return prisma.matchEvidence.upsert({
      where: { matchId_slot: { matchId, slot } },
      // Node's Buffer type isn't narrowed to Uint8Array<ArrayBuffer> the way
      // Prisma's generated Bytes input expects — a Buffer is a valid Bytes
      // value at runtime regardless, so this is a TS-only mismatch.
      create: { matchId, slot, ...rest } as unknown as Prisma.MatchEvidenceUncheckedCreateInput,
      update: rest as unknown as Prisma.MatchEvidenceUncheckedUpdateInput,
      select: publicSelect,
    });
  },

  delete(id: string) {
    return prisma.matchEvidence.delete({ where: { id } });
  },
};
